//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.MyReportingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MyReportingService", ConfigurationName="MyReportingService.IReport")]
    public interface IReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="MyReportingService/IReport/BuildProjectsReport", ReplyAction="MyReportingService/IReport/BuildProjectsReportResponse")]
        UIModels.ProjectViewModel[] BuildProjectsReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="MyReportingService/IReport/BuildProjectsReport", ReplyAction="MyReportingService/IReport/BuildProjectsReportResponse")]
        System.Threading.Tasks.Task<UIModels.ProjectViewModel[]> BuildProjectsReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportChannel : TestWebApp.MyReportingService.IReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportClient : System.ServiceModel.ClientBase<TestWebApp.MyReportingService.IReport>, TestWebApp.MyReportingService.IReport {
        
        public ReportClient() {
        }
        
        public ReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UIModels.ProjectViewModel[] BuildProjectsReport() {
            return base.Channel.BuildProjectsReport();
        }
        
        public System.Threading.Tasks.Task<UIModels.ProjectViewModel[]> BuildProjectsReportAsync() {
            return base.Channel.BuildProjectsReportAsync();
        }
    }
}
