//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.EmailReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MyReportingService", ConfigurationName="EmailReportService.IEmailReport")]
    public interface IEmailReport {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="MyReportingService/IEmailReport/SendReport")]
        void SendReport(string email);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="MyReportingService/IEmailReport/SendReport")]
        System.Threading.Tasks.Task SendReportAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailReportChannel : TestWebApp.EmailReportService.IEmailReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailReportClient : System.ServiceModel.ClientBase<TestWebApp.EmailReportService.IEmailReport>, TestWebApp.EmailReportService.IEmailReport {
        
        public EmailReportClient() {
        }
        
        public EmailReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendReport(string email) {
            base.Channel.SendReport(email);
        }
        
        public System.Threading.Tasks.Task SendReportAsync(string email) {
            return base.Channel.SendReportAsync(email);
        }
    }
}
